/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/CAvatar`; params?: Router.UnknownInputParams; } | { pathname: `/CBottomNav`; params?: Router.UnknownInputParams; } | { pathname: `/CButton`; params?: Router.UnknownInputParams; } | { pathname: `/CChip`; params?: Router.UnknownInputParams; } | { pathname: `/CIconButton`; params?: Router.UnknownInputParams; } | { pathname: `/CModal`; params?: Router.UnknownInputParams; } | { pathname: `/CRating`; params?: Router.UnknownInputParams; } | { pathname: `/CTextInput`; params?: Router.UnknownInputParams; } | { pathname: `/auth_github`; params?: Router.UnknownInputParams; } | { pathname: `/auth_google`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/oauthredirect`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/signin`; params?: Router.UnknownInputParams; } | { pathname: `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/Agenda`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/CAvatar`; params?: Router.UnknownOutputParams; } | { pathname: `/CBottomNav`; params?: Router.UnknownOutputParams; } | { pathname: `/CButton`; params?: Router.UnknownOutputParams; } | { pathname: `/CChip`; params?: Router.UnknownOutputParams; } | { pathname: `/CIconButton`; params?: Router.UnknownOutputParams; } | { pathname: `/CModal`; params?: Router.UnknownOutputParams; } | { pathname: `/CRating`; params?: Router.UnknownOutputParams; } | { pathname: `/CTextInput`; params?: Router.UnknownOutputParams; } | { pathname: `/auth_github`; params?: Router.UnknownOutputParams; } | { pathname: `/auth_google`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/oauthredirect`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/signin`; params?: Router.UnknownOutputParams; } | { pathname: `/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `/Agenda`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/CAvatar${`?${string}` | `#${string}` | ''}` | `/CBottomNav${`?${string}` | `#${string}` | ''}` | `/CButton${`?${string}` | `#${string}` | ''}` | `/CChip${`?${string}` | `#${string}` | ''}` | `/CIconButton${`?${string}` | `#${string}` | ''}` | `/CModal${`?${string}` | `#${string}` | ''}` | `/CRating${`?${string}` | `#${string}` | ''}` | `/CTextInput${`?${string}` | `#${string}` | ''}` | `/auth_github${`?${string}` | `#${string}` | ''}` | `/auth_google${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/oauthredirect${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/signin${`?${string}` | `#${string}` | ''}` | `/Profile${`?${string}` | `#${string}` | ''}` | `/Agenda${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/CAvatar`; params?: Router.UnknownInputParams; } | { pathname: `/CBottomNav`; params?: Router.UnknownInputParams; } | { pathname: `/CButton`; params?: Router.UnknownInputParams; } | { pathname: `/CChip`; params?: Router.UnknownInputParams; } | { pathname: `/CIconButton`; params?: Router.UnknownInputParams; } | { pathname: `/CModal`; params?: Router.UnknownInputParams; } | { pathname: `/CRating`; params?: Router.UnknownInputParams; } | { pathname: `/CTextInput`; params?: Router.UnknownInputParams; } | { pathname: `/auth_github`; params?: Router.UnknownInputParams; } | { pathname: `/auth_google`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/oauthredirect`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/signin`; params?: Router.UnknownInputParams; } | { pathname: `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/Agenda`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
